name: Run packer build on a template file

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
  AWS_ACCESS_DEMO_KEY_ID: ${{ secrets.AWS_ACCESS_DEMO_KEY }}
  AWS_SECRET_ACCESS_DEMO_KEY: ${{ secrets.AWS_SECRET_DEMO_KEY }}

# on:
#   pull_request:
#     branches: [ main ]
#     types: [ closed ]

on:  
  push:   
    branches: [a-09]    

jobs:
  packer_build:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: checkout code from branch
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name : Install dependencies
        run  : npm install 
      - name : Run test
        run  : npm test
    
      - name: build the application artifact 
        run: |
          zip -r webapp.zip ./
          pwd ./webapp        
      # - name: Use hashicrop Packer
      #   uses: hashicorp-contrib/setup-packer@v2
      # - name: Validate Packer
      #   run: packer validate ami.pkr.hcl
      # - name: Build image from template
      #   run: packer build ami.pkr.hcl

      - name: Configure AWS Credentials 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_DEMO_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_DEMO_KEY }}
          aws-region: us-east-1

      - name: create new launch template
        run: |
          aws ec2 get-launch-template-data --instance-id i-0ae7be9d319e39084 --query "LaunchTemplateData" >> instance-data.json
    

      - name: create new launch template
        run: |
          aws ec2 create-launch-template --launch-template-name my-template-for-auto-scaling --version-description version2 \
          --launch-template-data file://instance-data.json

      # - name: Update the autoscaling group 
      #   run: |
      #     aws autoscaling update-auto-scaling-group \
      #     --auto-scaling-group-name myVpcStack1-asg \
      #     --launch-template LaunchTemplateId=lt-05ccc528b833c3a18,Version='$Latest'   
      