name: Run packer build on a template file

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
  AWS_ACCESS_DEMO_KEY_ID: ${{ secrets.AWS_ACCESS_DEMO_KEY }}
  AWS_SECRET_ACCESS_DEMO_KEY: ${{ secrets.AWS_SECRET_DEMO_KEY }}

# on:
#   pull_request:
#     branches: [ main ]
#     types: [ closed ]

on:  
  push:   
    branches: [a-09]    

jobs:
  packer_build:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: checkout code from branch
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name : Install dependencies
        run  : npm install 
      - name : Run test
        run  : npm test
    
      - name: build the application artifact 
        run: |
          zip -r webapp.zip ./
          pwd ./webapp        
      - name: Use hashicrop Packer
        uses: hashicorp-contrib/setup-packer@v2
      - name: Validate Packer
        run: packer validate ami.pkr.hcl
      - name: Build image from template
        run: packer build ami.pkr.hcl

      - name: Create new launch template for autoscaling group
        run: |
          aws ec2 describe-launch-templates --launch-template-names myVpcStack1-launch-template