name: Run packer build on a template file

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
  AWS_ACCESS_DEMO_KEY_ID: ${{ secrets.AWS_ACCESS_DEMO_KEY }}
  AWS_SECRET_ACCESS_DEMO_KEY: ${{ secrets.AWS_SECRET_DEMO_KEY }}

# on:
#   pull_request:
#     branches: [ main ]
#     types: [ closed ]

on:  
  push:   
    branches: [a-09]    

jobs:
  packer_build:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Configure DEV AWS Credentials 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_DEV_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_DEV_KEY }}
          aws-region: us-east-1

      - name: checkout code from branch
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name : Install dependencies
        run  : npm install 

      - name : Run test
        run  : npm test
    
      - name: build the application artifact 
        run: |
          zip -r webapp.zip ./
          pwd ./webapp        

      - name: Use hashicrop Packer
        uses: hashicorp-contrib/setup-packer@v2

      - name: Validate Packer
        run: packer validate ami.pkr.hcl

      - name: Build image from template
        # run: packer build ami.pkr.hcl
        run: |
             AMI_ID=`packer build ami.pkr.hcl | tee >(cat 1>&2) | awk 'match($2, /ami-.*/) { print substr($2, RSTART, RLENGTH) }'`
             echo "AMI is ${AMI_ID}";
             aws ec2 create-launch-template-version --launch-template-name EC2-launch-template \
             --version-description version2 --source-version 1 --launch-template-data "ImageId=$AMI_ID"
     
      # - name: Update the autoscaling group 
      #   run: |
      #     aws autoscaling update-auto-scaling-group \
      #     --auto-scaling-group-name myVpcStack1-asg \
      #     --launch-template LaunchTemplateId=lt-05ccc528b833c3a18,Version='$Latest'   
      